### ISSUE TITLE
animate icon issue

### ISSUE THREAD

**Issue by Kotlin-GDE** [Aman-Malhotra/AnimateIconsFlutter#10]
hi

```
'package:flutter/src/material/tooltip.dart': Failed assertion: line 65 pos 15: 'message != null': is not true.
```

i use the latest version

**Comment by luckyrat** [comment]
The documentation is out of date. You now have to also define `startTooltip` and `endTooltip` properties.

**Comment by Aman-Malhotra** [comment]
`startTooltip` or `endTooltip` are optional parameters to the `AnimateIcons` widget and if not passed the widget will still work the same. I am closing this, you can comment and let know if this still persists.
