### ISSUE TITLE
[Feature Request] Add option to disable splash color and splash radius

### ISSUE THREAD

**Issue by antonygunawan94** [Aman-Malhotra/AnimateIconsFlutter#14]
Hello,

Is it okay for me to add these features to this package?

Thank you

**Comment by luca-colazzo** [comment]
This package is discontinued, so I made another one that does the same things as this one.
Feel free to have a look at it and use it.
I will make what's possible to fix any issue (and also I'm looking for a mantainer)

[pub.dev](https://pub.dev/packages/icons_animate/)
[Github repository](https://github.com/luca-colazzo/icons_animate)
