### ISSUE TITLE
Add tooltips support

### ISSUE THREAD

**Issue by arlucio** [Aman-Malhotra/AnimateIconsFlutter#3]
For web is pretty important to have a tooltip when you put the mouse over. 

Would be great if to have a `tooltip` field like in `IconButton` class.

**Comment by proninyaroslav** [comment]
You can use `Tooltip` widget.

**Comment by Aman-Malhotra** [comment]
Thanks for this req.
This has been added to the version `animate_icons: 1.0.0`. 
You can find it here https://pub.dev/packages/animate_icons/versions/1.0.0
